### ISSUE TITLE
Use Read Objects instead of 'screed' Records

### ISSUE THREAD

**Issue by emcd** [ged-lab/khmer#14]
If we can use objects of class 'Read' instead of 'screed' records, then we can delete the dependency upon 'screed', which will make 'khmer' more readily accessible, since people will not need to install 'screed' first or add it to their 'PYTHONPATH'.

If we do not do this before putting 'khmer' up on PyPI, then we definitely need to enforce 'screed' as prequisite and put that package up on PyPI.

**Comment by mr-c** [comment]
The screed dependency is not a burden anymore. I don't think it is a huge advantage to make dropping screed a priority.
