### ISSUE TITLE
Refactor Hash Size Warning Logic into Common Module

### ISSUE THREAD

**Issue by emcd** [ged-lab/khmer#21]
While manually breaking up lines which were too long, I encountered the same chunk of code copied and pasted many times over and over again in various scripts in scripts/ and sandbox/. We definitely want to place this in a common module for maintainability and reusability reasons.

**Comment by susinmotion** [comment]
working on this.

**Comment by susinmotion** [comment]
The threshold for what collision rate is too high varies in different parts of the code. What threshold(s) would you like to use? For now, I will pass the existing thresholds as an argument to the check function.

Here are the places the duplicate logic is found (or should be found?), and their thresholds:
Collect variants -- .2 (with a comment saying don't change)
Collect Reads -- .2 (with a comment saying don't change)
Sort by med. -- .8
do partition -- .15 (with a comment saying the actual max is .18, don't change)
filter abund. -- no check
load graph -- .15
load into c. -- no check
norm by med. -- no check
trim low abund. -- no check

**Comment by susinmotion** [comment]
Also!
Some places had the opportunity to force listed and others didn't. Is there a pattern to where where you'd like to allow for a force? Right now, I'm fixing as if you want to allow for a force at any time.

**Comment by mr-c** [comment]
Fixed by #944
