### ISSUE TITLE
Casava 1.8 pair checking in scripts/normalize-by-median, scripts/abund-filter and khmer/thread-utils

### ISSUE THREAD

**Issue by inodb** [ged-lab/khmer#23]
Hi! The read pair checking in scripts/normalize-by-median.py and scripts/abund-filter.py that relies on khmer/thread-utils.py doesn't work for paired reads from casava 1.8. I know that you can simply change it to old-style paired reads, but that is not really a proper solution. I wanted to update the paired checking myself but the problem is that the pair checking is done in a separate function in both files. Probably at some other locations as well. To me it makes more sense if screed gave you a function to check whether a record is a pair and also some functions to get a proper fasta/fastq representation of the read depending on whether the record is fasta or fastq since there are so many places in the scripts where this occurs. I would suggest a function that takes a record, parses the name + annotations of a read and tells you what sequencing technology it is and what type of read in a way that is easily extensible.

**Comment by ctb** [comment]
Fixed by #818.
