### ISSUE TITLE
migrate deprecated CObject to Capsules API

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#253]
The CObject system used to pass an opaque value was deprecated in Python 2.7.

http://docs.python.org/release/2.7/c-api/cobject.html

**Comment by Echelon9** [comment]
Claiming this one to work on.

As khmer already requires at a minimum Python 2.7.x, this can be implemented as a straight rip and replace. There should be no need to include a deprecated path, as all Python 2.7.x support Capsules API.

**Comment by mr-c** [comment]
Pinging @luizirber Is this still needed? (Re: #802 )

**Comment by luizirber** [comment]
@echelon9 see https://github.com/ged-lab/khmer/commit/7619f67e02b5e4fc70c7e0d3b4e9043c986f55ed
But based on #802 we are going to replace it with KSubsetPartition.

**Comment by Echelon9** [comment]
Okay, I'll reliquinsh doing further work on this then as #802 will remove the need for the changes.

**Comment by mr-c** [comment]
Thank you Rhys for your continuing contributions!

**Comment by ctb** [comment]
So... close? Close.
