### ISSUE TITLE
Callbacks into CPython VM during Multi-threaded Execution

### ISSUE THREAD

**Issue by emcd** [ged-lab/khmer#28]
We have various places where we wish to notify the user of progress being made during processing. In the original single-threaded model, callbacks were made from the C++ code doing the heavy-lifting to Python. That worked fine because there was never any issue with the GIL being released or acquired and the Python VM could be guaranteed to be in a consistent state. For multi-threaded operation, we cannot really guarantee that we will have the GIL when we need it without a great deal of hassle and a performance hit. Bad things will happen if C++ code attempts to callback into Python when the GIL is not acquired.

Here is a (not necessarily exhaustive) list of alternative mechanisms for user notification:
(*) Use C++ output streams. (We shouldn't have to worry about interference with Python streams since both are not in use at the same time. And, the way the reporting is structured is such that we shouldn't have to worry about multiple threads clobbering each other's output either. I'm +1 on this solution unless I think of something better.)
(*) Redesign the code to perform a certain amount of work, return to the Python wrapper for reporting, and then be resumed. (Potentially messy and would almost certainly break some existing interfaces. I'm -1 on this.)
(*) Setup a dedicated listener thread and send messages to it via an *intra*-process communication mechanism of some sort. (Would be a fun excuse to learn about ZeroMQ's inproc stuff, but probably not worth the hassle. So, I'm -1 on this as well.)
(*) Set up a synchronization barrier among the threads for getting the lock, reporting, and releasing the lock. (This _will_ hurt performance, possibly quite badly. It will also ruin the threading model-agnostic scheme we currently have. I'm definitely -1 on this.)

Other ideas welcome.

**Comment by mr-c** [comment]
This is no longer on our roadmap. Closing.
