### ISSUE TITLE
Merge Hashtable-related Scripts

### ISSUE THREAD

**Issue by emcd** [ged-lab/khmer#30]
There is a tremendous amount of copypasta involved in the various scripts using the Bloom filter. (Issue #21 was just the tip of the iceberg.) Unfortunately, the various strains have evolved upon divergent paths. For example, today I noticed that 'load-into-counting' insists upon a false positive rate of 0.2 or less and 'load-graph' insists upon a false positive rate of 0.15 or less. Unless I am missing something, it seems that you want both of these to be consistent and this is a code maintenance issue.

By an eyeball estimate, I would say that 90% of the DN^H^Hcode is the same in the two scripts mentioned above. I would rather merge them (and possibly some others) and setup some symlinks. (Git groks and honors symlinks on POSIX systems.) By inspecting 'sys.argv[0]', we can determine how the script was invoked and adjust available command-line arguments and behaviors accordingly. This may be a better approach from a maintainability perspective, even if it will make the master script a bit larger than any individual script we have now.

**Comment by ctb** [comment]
No longer relevant.
