### ISSUE TITLE
normalize-by-median.py fails on new-style Illumina headers

### ISSUE THREAD

**Issue by ctSkennerton** [ged-lab/khmer#341]
`normalize-by-median.py` makes the assumption that the identifier for the pairs end with either '1' or '2', which was the old way of doing things with illumina data.  But now with cassava 1.8 the pair identifiers are separated out with a space (e.g. `HWI-ST1035:120:C13A7ACXX:5:1101:1100:2030 1:N:0:GTCCGC`) and so you get nowhere.  Perhaps there could be an option to suppress read identifier validation?

**Comment by mr-c** [comment]
This is no longer a problem.
