### ISSUE TITLE
Cleanup C++ Extension Module

### ISSUE THREAD

**Issue by emcd** [ged-lab/khmer#38]
While debugging and figuring some things out about creating a Python type's class attributes from C, I realized that much of our extension module code is making life way harder on itself than need be and does not conform to best practices (as given by the CPython API documentation). In some cases, our existing practices result in objects not exposing all of the standard attributes that one would expect from a Python object. In other cases, we are simply writing code for things that various standard CPython API functions, in conjunction with certain type object slots, which have been available since at least Python 2.2, handle automatically.

While I am not advocating a massive housecleaning effort all at once, we should be looking to simplify and otherwise improve the various pieces of code as we touch them. In my humble estimation, we may be able to shave 500 or more lines from the extension module code and actually gain functionality in the process....

(This should be weighed against issue #13. Yes, I still have a SWIG itch I want to scratch.)

**Comment by mr-c** [comment]
See also #781 #728
