### ISSUE TITLE
Update docs to point to release notes and github repo near top

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#498]

**Comment by jennomics** [comment]
I am working on this issue!

**Comment by safay** [comment]
taking this, @jennomics, sorry!

**Comment by safay** [comment]
- [ ] Is it mergable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage.
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

**Comment by safay** [comment]
@mr-c: I think this is ready to go.  Will update ChangeLog once I get signal that this will be merged.

**Comment by mr-c** [comment]
Fixed by #953
