### ISSUE TITLE
Out of memory errors should fail gracefully

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#510]
Perhaps we should also check hash table parameters on the Python side to see if there is enough free memory.

**Comment by mr-c** [comment]
Oops, this is a duplicate of #111, which I had my own pull request to fix, #704 

@ctb, how shall we move forward? (see also https://github.com/ged-lab/khmer/pull/704#issuecomment-68304128)

**Comment by ctb** [comment]
On Thu, Feb 19, 2015 at 02:43:30PM -0800, Michael R. Crusoe wrote:
> Oops, this is a duplicate of #111, which I had my own pull request to fix, #704 
> 
> @ctb, how shall we move forward? (see also https://github.com/ged-lab/khmer/pull/704#issuecomment-68304128)

If @sherine.awad is willing to see this through, go for it.  Perhaps we can
have Linux-only tests?

**Comment by SherineAwad** [comment]
@ctb @mr-c  worked on this just for practicing github.  So whatever you decide is ok with me :)

**Comment by mr-c** [comment]
Sherine's work so far is a subset of #704. I can add the linux attributes to the tests and exclusions to the regular places.

@SherineAwad: sorry for wasting your time!

**Comment by SherineAwad** [comment]
No waste of time, its a more practice for github and I can assign myself something else :)

**Comment by mr-c** [comment]
Closing as this is a duplicate of #111
