### ISSUE TITLE
Fastq ID stripping

### ISSUE THREAD

**Issue by standage** [ged-lab/khmer#606]
The khmer scripts that I've used--interleaving, splitting, and diginorm--all strip Fastq IDs (probably the underlying screed library?). I've never considered this a problem before, but the newest version of FastQC uses the full Illumina read ID to identify systematic issues with [particular tiles in a flowcell](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/Help/3%20Analysis%20Modules/12%20Per%20Tile%20Sequence%20Quality.html). How much work would it be to implement an option that retains the original full Illumina Fastq IDs?

**Comment by Arhodes-CGRB-OSU** [comment]
I am gonna try to work this out

**Comment by ctb** [comment]
ping @Arhodes-CGRB-OSU can I liberate this issue for someone else to claim?

**Comment by Arhodes-CGRB-OSU** [comment]
Sure, my solution didn’t work the way it was supposed to.  Thanks for checking.

Ad

**Comment by ctb** [comment]
Fixed by #818.

**Comment by standage** [comment]
Just tested diginorm with the dataset that prompted this thread in the first place, and everything looks in order. Thanks! :+1:

**Comment by ctb** [comment]
thanks for forcing the issue :)
