### ISSUE TITLE
State of streaming sequence IO in khmer

### ISSUE THREAD

**Issue by bocajnotnef** [ged-lab/khmer#654]
**Currently:** There isn't any. Neither current screed (0.7) nor current read_parseres (not seqan) support streaming. 

**Soon:** When screed 0.7.1/screed 1.rc1 is cut/merged in we will have uncompressed and bz2 streaming functionality across all scripts that use screed. gzip streaming was never backported to python 2 and they've said they won't be porting it later. We could go and port it over ourselves.

When seqan is merged in we still won't have read_parser streaming since their high-level interfaces don't provide any streaming stuff. We can look into using lower-level APIs or bothering the seqan folks to make it work in their high-level stuff; I don't believe there's currently a lean either way.

So:
 - [x] screed uncompressed fasta
 - [x] screed uncompressed fastq
 - [ ] screed gzip fasta
 - [ ] screed gzip fastq
 - [x] screed bzip fasta
 - [x] screed bzip fastq
 - [x] read_parser uncompressed fasta
 - [x] read_parser uncompressed fastq
 - [x] read_parser gzip fasta
 - [x] read_parser gzip fastq
 - [x] read_parser bzip2 fasta
 - [x] read_parser bzip2 fastq

Comments/thoughts?

Relevant to #633
Space check over-riding mentioned in #618 would be useful here  (potentially?)

**Comment by ctb** [comment]
Do the checkboxes above need to be updated, @mr-c and @bocajnotnef ?

**Comment by mr-c** [comment]
Checkboxes have been updated.

**Comment by ctb** [comment]
@bocajnotnef can you update #700 and close this (or explain to me why we shouldn't)? thanks!

**Comment by bocajnotnef** [comment]
superseded by https://github.com/ged-lab/khmer/issues/700

**Comment by ctb** [comment]
@bocajnotnef was there anything to be updated on #700?

**Comment by bocajnotnef** [comment]
AFAIK no, it was accurate.
