### ISSUE TITLE
load-into-counting.py fails to detect invalid fasta input

### ISSUE THREAD

**Issue by vcepeda** [ged-lab/khmer#679]
load-into-counting.py should verify that the input files are valid. It checks if the name indicator (>) is missing from the fasta file, but doesn't check If invalid characters are included within the file.

**Comment by mr-c** [comment]
Hello @vcepeda. I think the khmer 1.3 release should solve your problem. Since I don't have any test data I'm going to close this issue for now. We would love to hear if it works for you either way and feel free to re-open this issue if it doesn't.

Thanks!
