### ISSUE TITLE
version 1.3 release

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#703]
- [x] add SeqAn to `doc/citations.txt` and `khmer/khmer_args.py`
-  ~~Document streaming mode & compressed file support.~~ No, soft launch
- [x] BaTLab
- [x] coverity scan
- [x] release checklist
- [x] acceptance test

**Comment by mr-c** [comment]
FYI: @ctb the acceptance test failed. Likely to be an issue with the test itself. Will investigate as I can this week.

**Comment by mr-c** [comment]
I've finally got the acceptance tests to run, though the trinity assembly has shrunk

```
+ /usr/local/share/khmer/sandbox/assemstats3.py 500 /mnt/work/trinity_out_dir/Trinity.fasta
** cutoff: 500
N       sum     max     filename
34      58087   4449    /mnt/work/trinity_out_dir/Trinity.fasta
```

**Comment by mr-c** [comment]
I feel a little weird about the changes to the Trinity assembly. Otherwise v1.3 is ready for release.

@ctb what do you say?

**Comment by ctb** [comment]
+1.

On Thu, Jan 08, 2015 at 09:52:35AM -0800, Michael R. Crusoe wrote:
> I feel a little weird about the changes to the Trinity assembly. Otherwise v1.3 is ready for release.
> 
> @ctb what do you say?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ged-lab/khmer/issues/703#issuecomment-69219096
-- 
C. Titus Brown, ctb@msu.edu

**Comment by mr-c** [comment]
+1 to release or +1 to being worried about the Trinity assembly?

**Comment by ctb** [comment]
+1 to release

**Comment by mr-c** [comment]
Done and done.
