### ISSUE TITLE
Disable __len__/len() of screed 'read' records.

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#705]
...alternatively, make len(read) == len(read.sequence)

Right now it gives the length of the dictionary which is stupid and, ahem, buggy.

**Comment by gpratt** [comment]
I'm working on this!

**Comment by ctb** [comment]
ok - note this is in the screed repo, not the khmer repo :)

github.com/ged-lab/screed

**Comment by gpratt** [comment]
Good to know :)

**Comment by gpratt** [comment]
I've got the fix, but I'm having trouble figuring out where I should put
the testing code.  test_fasta and test_fastq look promising, but I can't
figure out where the test for the general read object are, which is where I
think this belongs, any thoughts?

Gabriel Pratt
Bioinformatics Graduate Student, Yeo Lab
University of California San Diego

**Comment by ctb** [comment]
Just put it somewhere, for now :)

On Fri, Jan 09, 2015 at 11:51:02AM -0800, Gabriel Pratt wrote:
> I've got the fix, but I'm having trouble figuring out where I should put
> the testing code.  test_fasta and test_fastq look promising, but I can't
> figure out where the test for the general read object are, which is where I
> think this belongs, any thoughts?
> 
> Gabriel Pratt
> Bioinformatics Graduate Student, Yeo Lab
> University of California San Diego
> 
> On Thu, Jan 8, 2015 at 2:23 PM, C. Titus Brown <notifications@github.com>
> wrote:
> 
> > ok - note this is in the screed repo, not the khmer repo :)
> >
> > github.com/ged-lab/screed
> >
> > ???
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ged-lab/khmer/issues/705#issuecomment-69260972>.
> >
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ged-lab/khmer/issues/705#issuecomment-69388678
-- 
C. Titus Brown, ctb@msu.edu

**Comment by mr-c** [comment]
@gpratt Did you start a pull request?

**Comment by ctb** [comment]
cc @bocajnotnef

**Comment by mr-c** [comment]
Fixed by https://github.com/ged-lab/screed/issues/18
