### ISSUE TITLE
Install adds packages that corrupt other environments

### ISSUE THREAD

**Issue by moorepants** [ged-lab/khmer#729]
I installed khmer at the SWC workshop last week. In my case, I used a new conda environment instead of a virtualenv and then ran your install scripts. I recently noticed that all of my conda environments now had all these weird packages. Looks like your scripts install dependencies to `~/.local/lib/python2.7/site-packages/` which may be a valid place, but doesn't seem normal. Should all of that be installed into the environment's `local/lib/python2.7/site-packages`?

And just to note, I found your installation process different from most Python packages I've used. Out of installing hundreds of different packages I've never had this happen before. I'd also recommend building conda packages for your software, as users would be able to install it much easier without having to compile your C++ core (or any dependencies).

**Comment by moorepants** [comment]
I see, this comes from the pip `--user` flag. Shouldn't that be the users choice to use that flag? It is odd to force it on the user, especially when they may be using an environment that they want to control.

**Comment by mr-c** [comment]
Hello @moorepants, thanks for the report and using khmer in a workshop.

`pip install --user` only happens when developers execute `make install-dependencies`. If you just need to use the khmer module or our scripts then `pip install khmer` will only pull in one additional depenency: screed.

**Comment by mr-c** [comment]
As we do suggest that developers to install into a virtualenv we could remove the `--user` invocation. I'll test later. Thanks!

**Comment by moorepants** [comment]
Thanks!
