### ISSUE TITLE
SyntaxError during install

### ISSUE THREAD

**Issue by teshomem** [ged-lab/khmer#735]
Hi,

I am trying to install khmer in python3.4.1 but got this error:

 pip install khmer
Downloading/unpacking khmer
  Downloading khmer-1.3.tar.gz (7.8MB): 7.8MB downloaded
  Running setup.py (path:/work/users/pip_build_root/khmer/setup.py) egg_info for package khmer

    warning: no previously-included files found matching 'third-party/zlib/Makefile'
    warning: no previously-included files found matching 'third-party/zlib/zconf.h'
    warning: no previously-included files matching '*.orig' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking screed>=0.7.1 (from khmer)
  Downloading screed-0.7.1.tar.gz
  Running setup.py (path:/work/users/pip_build_root/screed/setup.py) egg_info for package screed
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/work/users/pip_build_root/screed/setup.py", line 5
        print '(WARNING: importing distutils, not setuptools!)'
                                                              ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/work/users/pip_build_root/screed/setup.py", line 5

    print '(WARNING: importing distutils, not setuptools!)'
                                                       
SyntaxError: invalid syntax

Thanks,
T.

**Comment by ctb** [comment]
Hi, khmer works with python 2.6 and python 2.7, but not yet Python 3.

best,
--titus

**Comment by ctb** [comment]
Version requirements updated in #741.

**Comment by teshomem** [comment]
Thank you :-)
