### ISSUE TITLE
[screed] tests don't use temporary directory; fail if screed/tests/ directory is read-only

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#748]
Which means users can't run the tests after install to a read-only directory 
Nor can Debian/Ubuntu test the package post install http://packaging.ubuntu.com/html/auto-pkg-test.html

**Comment by ctb** [comment]
See https://github.com/ged-lab/khmer/blob/master/tests/khmer_tst_utils.py#L33 for how we do this in khmer.

**Comment by bocajnotnef** [comment]
Nabbing this. Figure it's good to have in the 0.8 release.

**Comment by ctb** [comment]
Main question: what tests are actually writing to the directory?! Those are the ones that need to be fixed, and only those.

**Comment by bocajnotnef** [comment]
Note: This was deemed less important than getting the 0.8 release out, so I'll do this after the release is done.

**Comment by mr-c** [comment]
Fixed by https://github.com/ged-lab/screed/issues/30
