### ISSUE TITLE
We're throwing a sprint! Feb 19-20/23-25, 2015.

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#751]
Subscribe to this issue if you're interested (click on the 'subscribe' button (lower right)).

Blog post: http://ivory.idyll.org/blog/2015-another-khmer-sprint.html

See #446 for previous sprint/hackathon.

People who are interested in getting started on their own can see our "getting started" docs here: 

http://khmer.readthedocs.org/en/latest/dev/getting-started.html

We'll be using gitter for realtime chat: https://gitter.im/ged-lab/khmer

**Comment by Echelon9** [comment]
Any other prioritised areas to work on during the upcoming sprint?

**Comment by mr-c** [comment]
Announcement blogpost: http://ivory.idyll.org/blog/2015-another-khmer-sprint.html

**Comment by ctb** [comment]
@Echelon9 nothing specific; we have tons of issues, and lots of suggestions. Ask on the gitter channel if you're interested in a particular area!

**Comment by mr-c** [comment]
MSU participants: we are meeting up in BPS 2228. Feel free to join us here!

**Comment by mr-c** [comment]
Hangouts on air: https://plus.google.com/events/cf71pf33o0uqolvll6ta2u80ens

Participants are welcome to chat with us via https://gitter.im/ged-lab/khmer ; here on the GitHub issue tracker; or via the Hangout.

**Comment by mr-c** [comment]
Streaming video is back: https://plus.google.com/events/c1qevt9vsa6hj0bvv8off2aal90

**Comment by ctb** [comment]
New/good simple first-round sprint issues for folk who want to go through the process: #793, #801, #794, #795, #797, #798.

**Comment by Echelon9** [comment]
Have picked up a couple of these. Won't take them all however, as want to ensure first timers have enough readily found, easily resolveable issues to tackle.

**Comment by ctb** [comment]
Remaining and/or new good first-round sprint issues: #787, #784, #797, #824, #806.

**Comment by mr-c** [comment]
Closing as this was awesome. Thank you all!
