### ISSUE TITLE
Have a documented way to create new screed record objects.

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#767]
Right now you have to call

    screed.screedRecord._screed_record_dict()

-- perhaps

screed.Record(name=..., sequence=..., quality=...)

instead?

**Comment by sguermond** [comment]
Working on this.

**Comment by sguermond** [comment]
@mr-c Ready for review!

**Comment by mr-c** [comment]
Fixed by https://github.com/ged-lab/screed/issues/35
