### ISSUE TITLE
diagnose Mac OS X build errors

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#774]
@SherineAwad had some trouble building khmer on her latest OS X - diagnose.

Specifically,

     make CXX=c++ clean all

seems to have fixed things. Why? @brtaylor92 pointed out that on more recent OS X, gcc links to cc/g++ links to c++.

**Comment by mr-c** [comment]
This appears to be specific to her system.

**Comment by bede** [comment]
There's something odd happening for me too on OS 10.9.5. Following the getting started guide, `make test` output:
```
...
Using /Users/Bede/Research/Git/venv/lib/python2.7/site-packages/screed-0.7.1-py2.7.egg
Finished processing dependencies for khmer==1.3-116-gb63bd94
./setup.py nosetests
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'nosetests'
make: *** [test] Error 1
```

**Comment by bede** [comment]
Interestingly, the error seems to have changed since I accidentally ran `make install-dependencies` outside the virtualenv, before which `make test` it was complaining about Screed, not Nose
