### ISSUE TITLE
Have makefile print out list of targets

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#775]
a la

     https://github.com/swcarpentry/lesson-template/blob/gh-pages/Makefile           

@gvwilson quoth:

    The trick is to use '##' to mark comments you want printed, then have           
    'all' run                                                                       
                                                                                
    @sed -n 's/^##//p' $<                                                           
                                                                                
    to find and print those lines.  It's not automatic - comments can get out       
    of step - but it works well enough.

**Comment by gvwilson** [comment]
On 2015-02-15 10:46 AM, C. Titus Brown wrote:
> @gvwilson <https://github.com/gvwilson> quoth:
Actually, *I* "sayeth" - *you* "quoth".

**Comment by ctb** [comment]
https://www.google.com/search?q=quoth&oq=quoth

**Comment by mr-c** [comment]
+1

**Comment by standage** [comment]
I got this.
