### ISSUE TITLE
MinCount Sketch link is broken

### ISSUE THREAD

**Issue by r-gaia-cs** [ged-lab/khmer#778]
I'm getting 403 when try http://www.eecs.harvard.edu/~michaelm/CS222/countmin.pdf, the address associated with "MinCount Sketch" at `doc/introduction.txt`.

**Comment by mr-c** [comment]
@r-gaia-cs Welcome to the Sprint and thanks for the report. I'll look for a replacement.

**Comment by mr-c** [comment]
Does http://dimacs.rutgers.edu/~graham/pubs/papers/cm-full.pdf work for you? It matches the version on the WayBack machine: https://web.archive.org/web/20120401091555/http://www.eecs.harvard.edu/~michaelm/CS222/countmin.pdf

**Comment by r-gaia-cs** [comment]
> Does http://dimacs.rutgers.edu/~graham/pubs/papers/cm-full.pdf work for you?

@mr-c Yes.

**Comment by luizirber** [comment]
Is it 'safer' to use the Wayback Machine link (and avoid problems in the future?)

**Comment by mr-c** [comment]
I'm fine with the WayBack machine. The only thing better would be a
http://dx.doi.org/... URL.

**Comment by ctb** [comment]
Please use Count-Min Sketch as in the Cormode paper and http://www.ncbi.nlm.nih.gov/pubmed/25062443, and add that as a reference.

**Comment by ctb** [comment]
Fixed in #782.
