### ISSUE TITLE
Screed v0.8 thoughts

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#792]
- [x] Fix the khmer sandbox scripts (#787)
- [x] Run acceptance tests (this is for v0.8) as per #686 

cc @bocajnotnef

**Comment by bocajnotnef** [comment]
I'll start in on the sandbox scripts today/this weekend.

**Comment by bocajnotnef** [comment]
per verbal convo, I'll go clean up len and slicing issues ( #705  and #768, respectively) and @ctb will work on the sandbox scripts.
