### ISSUE TITLE
Add link to khmer-recipes and khmer-protocols from khmer docs.

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#793]
See https://github.com/ged-lab/khmer/issues/471#issuecomment-54153065

**Comment by SchwarzEM** [comment]
I am working on this issue...

**Comment by ctb** [comment]
To clarify: some of the best documentation for khmer is on the khmer-protocols.readthedocs.org and khmer-recipes.readthedocs.org web sites.  Links to these sites (together with a brief description of the content) should be added into the khmer user documentation somewhere.

The khmer documentation is in the khmer repository under doc/, and is in reStructuredText format.

**Comment by SchwarzEM** [comment]
OK, that took ridiculously long -- partly because of a slew of off-line distractions -- but I *may* have actually made the very minor change in doc/introduction.txt that this called for.

**Comment by ctb** [comment]
Fixed by #870
