### ISSUE TITLE
What is doc/scheme.txt in screed?

### ISSUE THREAD

**Issue by bocajnotnef** [ged-lab/khmer#800]
It's not referenced anywhere in the codebase and is making sphinx upset.

@ctb

**Comment by ctb** [comment]
On Fri, Feb 20, 2015 at 09:14:28AM -0800, bocajnotnef wrote:
> It's not referenced anywhere in the codebase and is making sphynx upset.
> 
> @ctb 

probably a typo; see schema.txt

--t

**Comment by bocajnotnef** [comment]
That's the file I meant. Grokking of it is lacking. Spinx being upset is not an issue, I just don't know what schema.txt is and/or if it matters.

File is:
```[ADMINISTRATION TABLE]
FIELDNAME TEXT | FIELDTYPE TEXT

[DICTIONARY TABLE]
ID INTEGER PRIMARY KEY | KEY FOR NAME QUERY TEXT | OTHER FIELDS...```

**Comment by ctb** [comment]
ahh. Delete it.

On Fri, Feb 20, 2015 at 09:36:12AM -0800, bocajnotnef wrote:
> That's the file I meant. Grokking of it is lacking. Spinx being upset is not an issue, I just don't know what schema.txt is and/or if it matters.
> 
> File is:
> ```[ADMINISTRATION TABLE]
> FIELDNAME TEXT | FIELDTYPE TEXT
> 
> [DICTIONARY TABLE]
> ID INTEGER PRIMARY KEY | KEY FOR NAME QUERY TEXT | OTHER FIELDS...```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ged-lab/khmer/issues/800#issuecomment-75284047
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by bocajnotnef** [comment]
Closed https://github.com/ged-lab/screed/pull/22
