### ISSUE TITLE
Correct spelling of 'mergeable' in dev checklist

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#801]
Fix spelling of "Is it mergable?" in http://khmer.readthedocs.org/en/v1.3/dev/coding-guidelines-and-review.html, which is in doc/dev/coding-guidelines-and-review.txt.

running a spellchecker in general might be good :)

**Comment by aditi9783** [comment]
I am working on this issue.

**Comment by ctb** [comment]
Closed by #804
