### ISSUE TITLE
Add citation information for HyperLogLog algorithm implementation

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#824]
- [x] add 'hll' entry into khmer/khmer_args.py, _algorithms dictionary
- [x] add call to 'info' with 'hll' in the algorithms list to sandbox/unique-kmers.py

**Comment by mr-c** [comment]
@ctb What citation should be listed for hll?

**Comment by alameldin** [comment]
i am working on this

**Comment by ctb** [comment]
On Mon, Feb 23, 2015 at 10:52:53AM -0800, Michael R. Crusoe wrote:
> @ctb What citation should be listed for hll?

Irber and Brown, unpublished.

**Comment by alameldin** [comment]
ready for review

**Comment by alameldin** [comment]
ready for review

**Comment by ctb** [comment]
Hi @alameldin, I will close #834 as it's out of date. And you should put the request for review in #845, not here!

**Comment by ctb** [comment]
Closed by #845. Thank you!
