### ISSUE TITLE
'make test' throwing error: "Could not find required distribution screed>=0.8rc1"

### ISSUE THREAD

**Issue by lexnederbragt** [ged-lab/khmer#829]
Hi,

I am following the instructions at http://khmer.readthedocs.org/en/latest/dev/getting-started.html. When I do 'write test', it ends with the above warning. It seems to gave installed screed-0.8-rc3:

```
Downloading https://testpypi.python.org/packages/source/s/screed/screed-0.8-rc3.tar.gz
Processing screed-0.8-rc3.tar.gz
[...]
Extracting screed-1.3_248_g662276c-py2.7.egg to /cluster/home/alexajo/khmer_env/lib/python2.7/site-packages
Adding screed 1.3-248-g662276c to easy-install.pth file

Installed /cluster/home/alexajo/khmer_env/lib/python2.7/site-packages/screed-1.3_248_g662276c-py2.7.egg
error: Could not find required distribution screed>=0.8rc1
make: *** [test] Error 1
```

Full output available if needed.

**Comment by ctb** [comment]
Hmm - does the fix in #803 work for you?

**Comment by lexnederbragt** [comment]
Should I wait for @mr-c 's announced fix, see https://github.com/ged-lab/khmer/issues/803#issuecomment-75577121?

**Comment by mr-c** [comment]
Fix is merged, no work around needed now. Sorry for the bother, @lexnederbragt
