### ISSUE TITLE
Switch scripts/ tabular output over to proper CSV formatting.

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#840]
All scripts that output tabular data should have a --csv option that outputs proper CSV, with column headers.  For khmer 1.x series, this will need to be an optional feature (due to Semantic Versioning); we can make it default for 2.x.

This has been done for count-median in #818 already, and is in process for abundance-dist in #831.

**Comment by drtamermansour** [comment]
I will do this also for scripts/abundance-dist-single.py

**Comment by ctb** [comment]
Do this to --

- [ ] count-overlap.py
- [ ] readstats.py (we should have a more naked table output from this anyway)

...and we should also update the dev docs for sandbox-to-script requirements.

**Comment by anotherthomas** [comment]
I'm working on readstats.py

**Comment by mr-c** [comment]
Fixed, thanks!
