### ISSUE TITLE
Add requirements to sandbox/ list --

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#846]
directly executable script names should be all lowercase (no CamelCase), and use '-' instead of '_'.

**Comment by ctb** [comment]
See http://khmer.readthedocs.org/en/latest/dev/scripts-and-sandbox.html for current; source file is in doc/dev/scripts-and-sandbox.txt.

**Comment by alameldin** [comment]
@ctb does it mean "only" renaming the scripts in sandbox/ to be all in lowercase?

**Comment by ctb** [comment]
I think they are all in lowercase, but they should use '-' instead of '_' as well in the filename.

**Comment by alameldin** [comment]
working on this

**Comment by ahaerpfer** [comment]
@mr-c could it be that this can be closed?  All sandbox-scripts are in lowercase and use '-' and *sandbox/README.rst* also looks OK and up to date.  Is there anything else to do?

**Comment by mr-c** [comment]
@ahaerpfer Good catch, thanks!
