### ISSUE TITLE
Regarding abundance-dist.py Documentation 

### ISSUE THREAD

**Issue by SherineAwad** [ged-lab/khmer#848]
In abundance-dist.py documentation, -s and -f do the exact same thing.

**Comment by SherineAwad** [comment]
Also in abundance-dist-single.py, -s and -f do the same thing.

**Comment by ctb** [comment]
(Although they do not in fact actually do the same thing - -s does what -f says it does.)

The problem seems to be that help' info for --force was copied w/o modification across the entire code base, sometimes incorrectly :).

See #647 for original PR.

**Comment by safay** [comment]
@mr-c: I think this was fixed by #929; can you please verify?

**Comment by mr-c** [comment]
Indeed. Good catch @safay. I am closing this issue. Thank you @SherineAwad for reporting this!
