### ISSUE TITLE
split-paired-reads.py breaks

### ISSUE THREAD

**Issue by macmanes** [ged-lab/khmer#873]
Turns out `split-paired-reads.py` breaks when stuff is in the trailing section of the fastQ header.. This is a fastQ file that breaks it. It's an output fastQ from Heng Li's bfc error correction tool: https://github.com/lh3/bfc

Here is an example:

    @SRR797058.11HWI-ST600:227:C0WR4ACXX:7:1101:20488:1997/1        ec:Z:0_0:1_0_1:0_0
    aTCCACCTTCTGGTCACCTAGGAGCTTTCCAACATCAGCAGTGACCTGGTCAGCCTGCTCTGTGAATGAATCTGTCATCTTAACAACCACGCTGGCACTGG
    +
    &+????????????????????????????????????????????????????????????????????????????????????????+????????++

Fails silently - outputs an empty set of read files..

`split-paired-reads.py corr.fq` -->  ` corr.fq.1` and ` corr.fq.2` are empty.

**Comment by ctb** [comment]
Hi Matt, what version of khmer are you using? A release or 'master'?

**Comment by ctb** [comment]
(I ask because we fixed just such a bug in #759.)

**Comment by macmanes** [comment]
I installed using `pip install khmer` on a ec2 instance that is no longer running. `pip search khmer` indicates v1.3 so I'm gonna go with that.  It's def. those trailing characters that breaks things, as running `awk '{print $1}' corr.fq > fixed.corr.fq` then split-paired.reads.py works fine.

**Comment by ctb** [comment]
On Tue, Mar 17, 2015 at 03:36:09AM -0700, Matt MacManes wrote:
> I installed using `pip install khmer` on a ec2 instance that is no longer running. `pip search khmer` indicates v1.3 so I'm gonna go with that.  It's def. those trailing characters that breaks things, as running `awk '{print $1}' corr.fq > fixed.corr.fq` then split-paired.reads.py works fine.  

OK. This should be fixed in the next release; I'd like to test against
master to be sure, thought, so if you could send me (privately is fine)
the top of a file that triggers the problem, I'll run it. thanks!

**Comment by anotherthomas** [comment]
On current master parsing fails with an error message: 
> split-paired-reads.py somefile.fastq
...
Unrecognized format for read pair information: SRR797058.11HWI-ST600:227:C0WR4ACXX:7:1101:20488:1997/1        ec:Z:0_0:1_0_1:0_0
Exiting.

It does create empty result files.

**Comment by macmanes** [comment]
I guess an error message is better than nothing, but better yet would be to ignore the training info in the fastq header.

**Comment by ahaerpfer** [comment]
I'll look into this and try to fix the parser.

**Comment by mr-c** [comment]
Fixed by #954
