### ISSUE TITLE
normalize-by-median multiple input files (possible bug)

### ISSUE THREAD

**Issue by drtamermansour** [ged-lab/khmer#908]
normalize-by-median.py: if the input files are multiple files of the same name (ofcourse in different folders), the program gives one .keep file for only one input file

**Comment by mr-c** [comment]
+1

**Comment by ctb** [comment]
On Sun, Apr 05, 2015 at 04:33:09AM -0700, Michael R. Crusoe wrote:
> +1

I think this is an obvious consequence of the way it works, and I'm -0
on further complicating the normalize-by-median.py code.  We should instead
provide better alternative (and soon, default) methods for handling output.

**Comment by mr-c** [comment]
How about added a warning?

**Comment by ctb** [comment]
On Sun, Apr 05, 2015 at 04:37:59AM -0700, Michael R. Crusoe wrote:
> How about added a warning?

*shrug* Doesn't help with the code complexity issue, but maybe we have to.

**Comment by elmbeech** [comment]
I gone fix this

**Comment by mr-c** [comment]
Fixed by #932
