### ISSUE TITLE
khmer doc file extensions trip up GitHub rich text editor

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#910]
I think if they had the '.rst' extension then GitHub would show the rich text editor and diffs. Needs investigating to see if Sphinx will be okay with that.

**Comment by ctb** [comment]
On Sun, Apr 05, 2015 at 03:05:55AM -0700, Michael R. Crusoe wrote:
> I think if they had the '.rst' extension then GitHub would show the rich text editor and diffs. Needs investigating to see if Sphinx will be okay with that.

Yes, this is straightforward; see source_suffix in doc/conf.py.  +1.

**Comment by mr-c** [comment]
Fixed by #912
