### ISSUE TITLE
clean up changes to sphinxcontrib-autoprogram and work with upstream to get them merged

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#913]
See also #620

**Comment by mr-c** [comment]
https://bitbucket.org/birkenfeld/sphinx-contrib/pull-request/59/enhance-autoprogram-include-usage-summary/diff

**Comment by anotherthomas** [comment]
I've resolved the conflicts against the default branch and added a test case.

**Comment by mr-c** [comment]
Fwoah, pull request merged. Thanks @anotherthomas !
