### ISSUE TITLE
[Screed] Screed's release checklist is missing the "Making Final Release" portion

### ISSUE THREAD

**Issue by bocajnotnef** [ged-lab/khmer#916]
As in, the analouge to http://khmer.readthedocs.org/en/v1.3/dev/release.html#how-to-make-a-final-release

**Comment by mr-c** [comment]
Note that there won't been a need for OS X specific instructions as Screed is pure python and the resulting wheel can be used on all platforms.

**Comment by bocajnotnef** [comment]
@mr-c Did you do the readthedocs stuff for screed?

**Comment by mr-c** [comment]
I think so. Does the basic URL redirect to the correct version for you?

**Comment by bocajnotnef** [comment]
It directs to "latest"

Also, just noticed that the 0.8 release notes aren't visible from readthedocs. I'll update the toctree in https://github.com/ged-lab/screed/pull/33

**Comment by bocajnotnef** [comment]
Scratch that, looks like there's a `.md` vs `.rst` issue. 

that is, the notes are `.md` and screed doesn't like them. Thoughts?

**Comment by mr-c** [comment]
See what I did for khmer :-)

**Comment by bocajnotnef** [comment]
Aha. Code borroed : 3

**Comment by mr-c** [comment]
Fixed by https://github.com/ged-lab/screed/issues/33
