### ISSUE TITLE
-T option in load-into-counting.py fails to execute

### ISSUE THREAD

**Issue by drtamermansour** [ged-lab/khmer#918]
load-into-counting.py works fine with --threads but fails to execute with -T

**Comment by mr-c** [comment]
Hey @drtamermansour, I can't reproduce this.

What is the exact command line, what version of khmer, and where are you running this?

``` bash
(env)mcrusoe@athyra:~/khmer/gl-master$ load-into-counting.py -k 20 -x 5e7 -T 4 out.ct data/100k-filtered.fa 

|| This is the script 'load-into-counting.py' in khmer.
|| You are running khmer version 1.4-rc1-12-gdc2eb5d
|| You are also using screed version 0.8
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||   * Q Zhang et al., http://dx.doi.org/10.1371/journal.pone.0101271
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.


PARAMETERS:
 - kmer size =    20            (-k)
 - n tables =     4             (-N)
 - min tablesize = 5e+07        (-x)

Estimated memory usage is 2e+08 bytes (n_tables x min_tablesize)
--------
Saving k-mer counting table to out.ct
Loading kmers from sequences in ['data/100k-filtered.fa']
making k-mer counting table
consuming input data/100k-filtered.fa
saving out.ct
fp rate estimated to be 0.000
DONE.
wrote to: out.ct.info
(env)mcrusoe@athyra:~/khmer/gl-master$ load-into-counting.py -k 20 -x 5e7 --threads 4 out.ct.2 data/100k-filtered.fa                        

|| This is the script 'load-into-counting.py' in khmer.
|| You are running khmer version 1.4-rc1-12-gdc2eb5d
|| You are also using screed version 0.8
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||   * Q Zhang et al., http://dx.doi.org/10.1371/journal.pone.0101271
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.


PARAMETERS:
 - kmer size =    20            (-k)
 - n tables =     4             (-N)
 - min tablesize = 5e+07        (-x)

Estimated memory usage is 2e+08 bytes (n_tables x min_tablesize)
--------
Saving k-mer counting table to out.ct.2
Loading kmers from sequences in ['data/100k-filtered.fa']
making k-mer counting table
consuming input data/100k-filtered.fa
saving out.ct.2
fp rate estimated to be 0.000
DONE.
wrote to: out.ct.2.info
(env)mcrusoe@athyra:~/khmer/gl-master$ diff out.ct out.ct.2
(env)mcrusoe@athyra:~/khmer/gl-master$ 
```

**Comment by drtamermansour** [comment]
I am using the MSU-HPC. Here is when it works:

(env)[mansourt@dev-intel10 temp-loadintocounting]$ load-into-counting.py -k 17 -N 4 -x 3e7 --threads 4 reads.kt reads.fq 

|| This is the script 'load-into-counting.py' in khmer.
|| You are running khmer version 1.4-rc1-3-g3c2f0bd
|| You are also using screed version 0.8-rc4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||   * Q Zhang et al., http://dx.doi.org/10.1371/journal.pone.0101271
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.


PARAMETERS:
 - kmer size =    17            (-k)
 - n tables =     4             (-N)
 - min tablesize = 3e+07        (-x)

Estimated memory usage is 1.2e+08 bytes (n_tables x min_tablesize)
--------
Saving k-mer counting table to reads.kt
Loading kmers from sequences in ['reads.fq']
making k-mer counting table
consuming input reads.fq
saving reads.kt
fp rate estimated to be 0.000
DONE.
wrote to: reads.kt.info



And here is when it fails

(env)[mansourt@dev-intel10 temp-loadintocounting]$ load-into-counting.py -k 17 -N 4 -x 3e7 –T 4 --report-total-kmers reads.kt reads.fq 

|| This is the script 'load-into-counting.py' in khmer.
|| You are running khmer version 1.4-rc1-3-g3c2f0bd
|| You are also using screed version 0.8-rc4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||   * Q Zhang et al., http://dx.doi.org/10.1371/journal.pone.0101271
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.

usage: load-into-counting.py [-h] [--version] [-q] [--ksize KSIZE]
                             [--n_tables N_TABLES]
                             [--min-tablesize MIN_TABLESIZE]
                             [--threads THREADS] [-b] [--summary-info FORMAT]
                             [--report-total-kmers] [-f]
                             output_countingtable_filename
                             input_sequence_filename
                             [input_sequence_filename ...]
load-into-counting.py: error: unrecognized arguments: reads.kt reads.fq



If you tried without “—report-total-kmers”, you will get a different failure response 

(env)[mansourt@dev-intel10 temp-loadintocounting]$ load-into-counting.py -k 17 -N 4 -x 3e7 –T 4 reads.kt reads.fq 

|| This is the script 'load-into-counting.py' in khmer.
|| You are running khmer version 1.4-rc1-3-g3c2f0bd
|| You are also using screed version 0.8-rc4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||   * Q Zhang et al., http://dx.doi.org/10.1371/journal.pone.0101271
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.


PARAMETERS:
 - kmer size =    17            (-k)
 - n tables =     4             (-N)
 - min tablesize = 3e+07        (-x)

Estimated memory usage is 1.2e+08 bytes (n_tables x min_tablesize)
--------
ERROR: Input file 4 does not exist
Exiting

**Comment by mr-c** [comment]
Compare `–T` and `-T`. They are different dashes. Are you copying and
pasting from a Microsoft Word document or other print oriented text editor?

Try typing out dash T.

**Comment by drtamermansour** [comment]
You are right. Actually it is the default txt editor of Mac doing wired
auto-correction.
Sorry



On Mon, Apr 6, 2015 at 10:56 AM, Michael R. Crusoe <notifications@github.com

**Comment by mr-c** [comment]
No worries. I'm happy to be helpful! Thank you for reporting this issue.
