### ISSUE TITLE
khmer.kfile.check_file_status needs to be renamed to reflect that input files are the target of the function

### ISSUE THREAD

**Issue by mr-c** [ged-lab/khmer#927]

**Comment by proteasome** [comment]
I am working on this issue.

**Comment by mr-c** [comment]
`check_input_files` would be a great name

**Comment by proteasome** [comment]
? this seems to be confounded with 
 check_file_status->check_input_files #941

**Comment by proteasome** [comment]
- [ ] Is it mergeable?
- [ ] Did it pass the tests?
- [ ] If it introduces new functionality in scripts/ is it tested?
  Check for code coverage with `make clean diff-cover`
- [ ] Is it well formatted? Look at `make pep8`, `make diff_pylint_report`,
  `make cppcheck`, and `make doc` output. Use `make format` and manual
  fixing as needed.
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Is it documented in the ChangeLog?
  http://en.wikipedia.org/wiki/Changelog#Format
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Is the Copyright year up to date?

**Comment by proteasome** [comment]
ready for review!

**Comment by mr-c** [comment]
Fixed in #941
