### ISSUE TITLE
Add "Is Copyright up to date?" to commiter checklist

### ISSUE THREAD

**Issue by Magentashades** [ged-lab/khmer#937]
Would it make sense to add another item to the commit checklist to make sure that the copyright is up to date when making the commit?

**Comment by mr-c** [comment]
+1

**Comment by sguermond** [comment]
Working on this.

**Comment by wking** [comment]
If you want to automate copyright year bumps and author information,
you might be interested in my update-copyright package [1].  I'm happy
to work up a PR with the .update-copyright.conf if that sounds useful.

[1]: https://pypi.python.org/pypi/update-copyright/

**Comment by Magentashades** [comment]
This is a cool script. One of the specifications for updating the copyright
headers was that the change be substantial in some way, which a git commit
doesn't necessarily identify (and seems to often be a false positive) hence
the human parsing effort.

**Comment by wking** [comment]
On Tue, Apr 14, 2015 at 09:02:43AM -0700, Sarah Fernandez wrote:
> This is a cool script. One of the specifications for updating the
> copyright headers was that the change be substantial in some way,
> which a git commit doesn't necessarily identify (and seems to often
> be a false positive) hence the human parsing effort.

Fair enough, although for open source projects I don't see much harm
in being a bit liberal in handing out copyright ownership, especially
since “substantial in some way” is so vague…

**Comment by mr-c** [comment]
Fixed by #940
